### PR TITLE
PTX-1703 Added storage policy methods in px_utils

### PR DESCRIPTION
**Pull request by jitupawar22**
- storage policy creation
 - Setting default storage policy
This will help in creation of repl = 2 volumes for other frameworks volumes

Signed-off-by: Jitendra Pawar <jitendra@portworx.com>

### CODE REVIEW

**Comment by disrani-px** [comment]
We need to set 'repl=2' in each of the frameworks instead of the storage policy.

**Comment by jitupawar22** [comment]
I have removed pxinstall tag for the storage policy. So it will become regular test for portworx framework. For repl=2 lets address it separately through every frameworks "portworx volume options"

**Comment by disrani-px** [comment]
Just creating a storage policy doesn't really test anything. We should have separate tests for the following:
1. Set storage policy and then start Cassandra to make sure the policy is being enforced
2. Set repl=2 in each of the frameworks

**Comment by jitupawar22** [comment]
Currently we do not have support for invocation of other frameworks tests from portworx framework testsuite. We need to figure out how that can be done and then there could be many testcases as you have mentioned in point number 1.  Though I could think of one test case - 
Setting up storage policy for old Px-image and upgrading the px-image to newer and verify volumes gets created as per storage policy. Please let me know if that make sense I will update the PR accordingly. 

On the other hand I will add support for setting "repl=2" in each framework in separate PR.

**Review by disrani-px — APPROVED** [review]

**Pull request merged**
